id: A5BBF45B2
title: Prayer to His Holiness the Dalai Lama
type: translation
pechas:
- IBE0C4256
- I5E22FEA8
- I32393400
- I64897A74
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:15.096191
  last_modified_at: 2023-01-04 11:54:15.096198
  collections:
  - Fourteenth Dalai Lama Series
  - Works of Tibetan Masters
alignment_to_base:
  IBE0C4256/6105: C04A
  I5E22FEA8/D8FA: C04A
  I32393400/5C49: C04A
  I64897A74/BCFC: C04A
